### ISSUE TITLE
Lol, hi there.

### ISSUE THREAD

**Issue by mindrage** [leafo/ludum-dare-40#1]
Good luck on your ludum dare.
Didn't know you were such a badass by participating 11 times now.

I just wonder if you have any resources to point usage with LuaJIT FFI in moonscript?
Kinda researched to get started with moonscript a bit and came across your post at https://news.ycombinator.com/item?id=144414920.

Sorry if this communication method is a bit wierd XD, just thought it was a fun thing.

**Comment by leafo** [comment]
I've written a handful of ffi based libraries for Lua in MoonScript. MoonScript is just Lua after being compiled, so there's really no difference than doing it in Lua, you just get MoonScript's features.

https://github.com/leafo/magick
https://github.com/leafo/giflib
https://github.com/leafo/luajit-geoip
